import json
import re
import time

import boto3

from app.core.config import settings

def _bedrock_boto3_kwargs() -> dict:
    if settings.BEDROCK_API_KEY:
        return {"aws_access_key_id": "dummy", "aws_secret_access_key": "dummy"}
    if not settings.BEDROCK_CROSS_ACCOUNT_ROLE_ARN:
        return {}
    sts = boto3.client("sts", region_name=settings.AWS_REGION)
    assumed = sts.assume_role(
        RoleArn=settings.BEDROCK_CROSS_ACCOUNT_ROLE_ARN,
        RoleSessionName="stagecraft-worker-bedrock",
        DurationSeconds=3600,
    )
    creds = assumed["Credentials"]
    return {
        "aws_access_key_id": creds["AccessKeyId"],
        "aws_secret_access_key": creds["SecretAccessKey"],
        "aws_session_token": creds["SessionToken"],
    }

def _apply_bedrock_api_key(client) -> None:
    if not settings.BEDROCK_API_KEY:
        return
    api_key = settings.BEDROCK_API_KEY

    def _inject_bearer(request, **kwargs):
        request.headers["Authorization"] = f"Bearer {api_key}"

    client.meta.events.register("before-send.bedrock-runtime", _inject_bearer)

class BedrockRemediationClient:

    def __init__(self) -> None:
        self._client = boto3.client(
            "bedrock-runtime",
            region_name=settings.AWS_REGION,
            **_bedrock_boto3_kwargs(),
        )
        _apply_bedrock_api_key(self._client)
        self._model_id = settings.BEDROCK_MODEL_ID

    def _build_prompt(
        self,
        workflow_yaml: str,
        logs: str,
        workflow_name: str,
        repo: str,
    ) -> str:
        return f"""You are an expert DevOps engineer specializing in GitHub Actions CI/CD pipelines.

A workflow named "{workflow_name}" in repository "{repo}" has failed.

## Failed Workflow YAML
```yaml
{workflow_yaml}
```

## Failure Logs (last 300 lines)
```
{logs}
```

Analyze the failure and provide a fix. Respond with ONLY valid JSON in this exact format:
{{
  "root_cause": "One clear sentence describing why the workflow failed",
  "fixed_yaml": "The complete corrected workflow YAML as a string",
  "pr_title": "fix: <short description of the fix>",
  "pr_description": "## Root Cause\\n<root_cause>\\n\\n## Changes Made\\n- bullet point changes\\n\\n## Testing\\nThis fix was generated by Stagecraft AI using AWS Bedrock (Claude). Please review the changes before merging.\\n\\n> 🤖 Auto-generated by Stagecraft"
}}"""

    def analyze_failure(
        self,
        workflow_yaml: str,
        logs: str,
        workflow_name: str,
        repo: str,
    ) -> dict:
        prompt = self._build_prompt(workflow_yaml, logs, workflow_name, repo)

        max_retries = 2
        last_exception: Exception | None = None

        for attempt in range(max_retries + 1):
            try:
                response = self._client.converse(
                    modelId=self._model_id,
                    messages=[
                        {
                            "role": "user",
                            "content": [{"text": prompt}],
                        }
                    ],
                    inferenceConfig={"maxTokens": 8192},

                )
                raw_text: str = response["output"]["message"]["content"][0]["text"].strip()

                raw_text = re.sub(r"^```(?:json)?\s*", "", raw_text, flags=re.MULTILINE)
                raw_text = re.sub(r"\s*```$", "", raw_text, flags=re.MULTILINE)
                raw_text = raw_text.strip()

                parsed: dict = json.loads(raw_text)

                required_keys = {"root_cause", "fixed_yaml", "pr_title", "pr_description"}
                missing = required_keys - set(parsed.keys())
                if missing:
                    raise ValueError(f"Bedrock response missing keys: {missing}")

                return parsed

            except self._client.exceptions.ThrottlingException as exc:
                last_exception = exc
                if attempt < max_retries:
                    wait = 2 ** (attempt + 1)
                    time.sleep(wait)
                    continue
                raise

            except (json.JSONDecodeError, ValueError, KeyError) as exc:
                _raw = locals().get("raw_text", "<unavailable>")
                raise RuntimeError(
                    f"Failed to parse Bedrock response as valid JSON: {exc}\n"
                    f"Raw response: {_raw}"
                ) from exc

        raise RuntimeError("Bedrock invocation failed after retries") from last_exception

    def generate_yaml_fix(
        self,
        workflow_yaml: str,
        root_cause: str,
        failure_category: str = "UNKNOWN",
        logs: str = "",
        few_shot_context: str = "",
    ) -> str:

        _CATEGORY_HINTS = {
            "DEPENDENCY_VERSION": (
                "The issue is an invalid/outdated dependency or language version. "
                "Replace it with the correct stable version from the canonical table below."
            ),
            "AUTH_FAILURE": (
                "The issue is authentication. Common fixes: correct a mistyped secret name "
                "(e.g. ${{ secrets.GITHUB_TOKEN }} not GITHUB_TOKENS), add a missing "
                "permissions block, or fix an env var that should reference a secret."
            ),
            "NETWORK_TIMEOUT": (
                "The issue is a network timeout. Common fixes: add --retry / --connect-timeout "
                "flags to curl/wget commands, increase timeout values, or add a 'continue-on-error: true' "
                "with a retry step."
            ),
            "CONFIG_ERROR": (
                "The issue is a YAML config error. Fix the invalid key name, indentation, "
                "or syntax that caused the failure."
            ),
            "TEST_FAILURE": (
                "Tests failed. Fix the workflow step that runs tests — e.g. correct the test "
                "command, install missing test dependencies, or set required env vars."
            ),
            "BUILD_ERROR": (
                "The build failed. Fix the build step — e.g. add missing build dependencies, "
                "correct the build command, or fix a missing env var."
            ),
            "LINT_ERROR": (
                "A linting/formatting check failed. Fix the lint step — e.g. update the linter "
                "version, correct the lint command, or add a step to auto-fix."
            ),
            "PERMISSION_ERROR": (
                "A permissions error occurred. Add or correct the 'permissions:' block in the "
                "workflow or job, e.g. 'contents: read', 'pull-requests: write'."
            ),
            "UNKNOWN": (
                "Apply the minimal change to the YAML that directly addresses the root cause."
            ),
        }
        category_hint = _CATEGORY_HINTS.get(failure_category, _CATEGORY_HINTS["UNKNOWN"])

        logs_section = (
            f"\nRELEVANT FAILURE LOGS (last 100 lines):\n{logs[-3000:]}\n"
            if logs else ""
        )

        few_shot_section = (
            f"\nPREVIOUSLY ACCEPTED FIXES FOR SIMILAR FAILURES (use as style/pattern reference):\n{few_shot_context}\n"
            if few_shot_context else ""
        )

        prompt = (
            "You are an expert GitHub Actions DevOps engineer fixing a broken CI workflow.\n\n"
            f"FAILURE CATEGORY: {failure_category}\n"
            f"ROOT CAUSE: {root_cause}\n"
            f"FIX GUIDANCE: {category_hint}\n"
            f"{logs_section}"
            f"{few_shot_section}\n"
            "ORIGINAL FAILING YAML:\n"
            "```yaml\n"
            f"{workflow_yaml}\n"
            "```\n\n"
            "CANONICAL STABLE VERSIONS (reference for DEPENDENCY_VERSION fixes):\n"
            "  Python → 3.12 | Node.js → 20 | Java → 21 | Ruby → 3.3 | Go → 1.22\n"
            "  actions/checkout → v4 | actions/setup-python → v5 | actions/setup-node → v4\n\n"
            "STRICT OUTPUT RULES:\n"
            "1. Output ONLY the corrected YAML. Zero prose. Zero explanation.\n"
            "2. Do NOT use markdown fences (no ```).\n"
            "3. Do NOT ask questions. Do NOT say 'I need to ask' or 'please provide'.\n"
            "4. Make the MINIMAL change required — copy every other line byte-for-byte, "
            "including its exact leading whitespace.\n"
            "5. Sibling keys in the same mapping MUST share the exact same indentation as "
            "each other and as they had in the original file. Never shift the indentation "
            "of a line you are not changing, even by one space.\n"
            "6. If a version is clearly invalid (e.g. '99', '0'), replace with the stable version above.\n"
            "7. Never use emoji characters anywhere in the output.\n"
            "8. Never add a comment (# ...) that did not already exist in the original YAML -- no "
            "explanatory, celebratory, or narrating comments about the fix.\n"
            "Output the corrected YAML now:"
        )
        max_retries = 2
        for attempt in range(max_retries + 1):
            try:
                response = self._client.converse(
                    modelId=self._model_id,
                    messages=[{"role": "user", "content": [{"text": prompt}]}],
                    inferenceConfig={"maxTokens": 8192, "temperature": 0},

                )
                raw: str = response["output"]["message"]["content"][0]["text"].strip()

                if raw.startswith("```"):
                    lines = raw.splitlines()
                    raw = "\n".join(l for l in lines if not l.startswith("```")).strip()
                if not raw:
                    raise ValueError("Model returned empty YAML fix")
                return raw
            except self._client.exceptions.ThrottlingException:
                if attempt < max_retries:
                    time.sleep(2 ** (attempt + 1))
                    continue
                raise
        raise RuntimeError("generate_yaml_fix: Bedrock invocation failed after retries")

    def correct_yaml_syntax(
        self,
        original_yaml: str,
        malformed_yaml: str,
        error_message: str,
    ) -> str:
        prompt = (
            "You are an expert GitHub Actions DevOps engineer. A YAML parser failed to parse a suggested YAML fix.\n\n"
            "ORIGINAL FAILING WORKFLOW:\n"
            "```yaml\n"
            f"{original_yaml}\n"
            "```\n\n"
            "YOUR PREVIOUS SUGGESTED FIX (CONTAINING SYNTAX ERRORS):\n"
            "```yaml\n"
            f"{malformed_yaml}\n"
            "```\n\n"
            "YAML PARSER ERROR MESSAGE (note the line/column it points to):\n"
            "```\n"
            f"{error_message}\n"
            "```\n\n"
            "STRICT OUTPUT RULES:\n"
            "1. Fix ONLY the syntax/parsing error at the line/column the parser error message "
            "points to. A common cause is indentation drift: a key was shifted by one or more "
            "spaces relative to its sibling keys in the same mapping — if so, realign it to "
            "match its siblings exactly.\n"
            "2. Output ONLY the corrected YAML. Zero prose. Zero markdown code fences (no ```).\n"
            "3. Copy every other line byte-for-byte, including its exact leading whitespace. "
            "Do not re-indent or otherwise touch any line the error message doesn't point to.\n"
            "4. Never use emoji characters or add a new comment (# ...) that did not already exist "
            "in the original YAML.\n"
            "Output the corrected YAML now:"
        )

        max_retries = 2
        for attempt in range(max_retries + 1):
            try:
                response = self._client.converse(
                    modelId=self._model_id,
                    messages=[{"role": "user", "content": [{"text": prompt}]}],
                    inferenceConfig={"maxTokens": 8192, "temperature": 0},

                )
                raw: str = response["output"]["message"]["content"][0]["text"].strip()

                if raw.startswith("```"):
                    lines = raw.splitlines()
                    raw = "\n".join(l for l in lines if not l.startswith("```")).strip()
                if not raw:
                    raise ValueError("Model returned empty corrected YAML fix")
                return raw
            except self._client.exceptions.ThrottlingException:
                if attempt < max_retries:
                    time.sleep(2 ** (attempt + 1))
                    continue
                raise
        raise RuntimeError("correct_yaml_syntax: Bedrock invocation failed after retries")

    def _invoke_json(
        self, prompt: str, required_keys: set[str], max_tokens: int = 2048, system_prompt: str | None = None
    ) -> dict:
        max_retries = 2
        last_exception: Exception | None = None
        for attempt in range(max_retries + 1):
            try:
                kwargs: dict = {
                    "modelId": self._model_id,
                    "messages": [{"role": "user", "content": [{"text": prompt}]}],
                    "inferenceConfig": {"maxTokens": max_tokens},
                }
                if system_prompt:
                    kwargs["system"] = [{"text": system_prompt}]
                response = self._client.converse(**kwargs)
                raw_text: str = response["output"]["message"]["content"][0]["text"].strip()
                raw_text = re.sub(r"^```(?:json)?\s*", "", raw_text, flags=re.MULTILINE)
                raw_text = re.sub(r"\s*```$", "", raw_text, flags=re.MULTILINE)
                raw_text = raw_text.strip()
                parsed: dict = json.loads(raw_text)
                missing = required_keys - set(parsed.keys())
                if missing:
                    raise ValueError(f"Bedrock response missing keys: {missing}")
                return parsed
            except self._client.exceptions.ThrottlingException as exc:
                last_exception = exc
                if attempt < max_retries:
                    time.sleep(2 ** (attempt + 1))
                    continue
                raise
            except (json.JSONDecodeError, ValueError, KeyError) as exc:
                _raw = locals().get("raw_text", "<unavailable>")
                raise RuntimeError(
                    f"Failed to parse Bedrock response as valid JSON: {exc}\nRaw response: {_raw}"
                ) from exc
        raise RuntimeError("Bedrock invocation failed after retries") from last_exception

    def narrate_template_diff(self, diff: dict, workflow_file: str, template_name: str) -> str:
        prompt = f"""You are reviewing a GitHub Actions workflow's adherence to your organization's approved CI template.

Workflow: {workflow_file}
Template: {template_name}
Adoption score: {diff['adoption_score']}/100
Missing components (required by the template, absent here): {diff['missing_components'] or 'none'}
Extra components (present here, not in the template): {diff['extra_components'] or 'none'}
Version drift: {diff['version_drift'] or 'none'}

In 2-3 sentences, explain in plain English what this gap likely means in practice and whether a reviewer should be concerned -- e.g. a missing security-scan step is a real risk worth flagging, an extra step that's harmless project-specific tooling is not. Respond with ONLY valid JSON in this exact format: {{"narrative": "..."}}"""
        result = self._invoke_json(prompt, required_keys={"narrative"}, max_tokens=512)
        return result["narrative"]

    def narrate_vulnerability_rca(self, finding: dict, app_context: dict | None, blast_radius: dict) -> str:
        context_lines = "none on file"
        if app_context:
            context_lines = (
                f"risk tier: {app_context.get('risk_tier') or 'unset'}, "
                f"regulatory scope: {app_context.get('regulatory_scope') or []}"
            )
        prompt = f"""You are summarizing a security finding for an engineer, based on structured evidence already gathered by deterministic tools -- do not invent or re-diagnose the vulnerability yourself, only explain it.

Source: {finding.get('alert_source')}
Identifier: {finding.get('identifier') or 'n/a'}
Package: {finding.get('package_name') or 'n/a'}
Severity (raw): {finding.get('severity') or 'unknown'}
Severity (in application context): {finding.get('severity_in_context') or 'unknown'}
Description: {finding.get('description') or 'n/a'}
Application context: {context_lines}
Blast radius: {blast_radius.get('affected_repos', [])} repos, {blast_radius.get('affected_files', [])} files reference this package

In 3-4 sentences, explain what this finding means in practice for this application, why the severity is what it is given the context above, and what's at stake if left unaddressed. Respond with ONLY valid JSON in this exact format: {{"summary": "..."}}"""
        result = self._invoke_json(prompt, required_keys={"summary"}, max_tokens=512)
        return result["summary"]

    def plan_dependency_fix(
        self,
        finding: dict,
        order_summary: str,
        system_prompt: str | None,
        skill_context: str,
    ) -> dict:
        """Used by the Vulnerability Remediation custom agent: decides whether to
        proceed with a dependency-ordered fix PR (honoring any user-authored
        skill-file constraints) and writes the PR title/body. system_prompt and
        skill_context both come from the user-editable CustomAgentConfig."""
        default_system = (
            "You are the Vulnerability Remediation agent for StageCraft, a CI/CD governance "
            "platform. You raise dependency-ordered fix PRs for vulnerable packages. Respect "
            "any constraints given to you below and never fabricate vulnerability details -- "
            "only use the structured evidence provided in the user message."
        )
        system = f"{default_system}\n\n{system_prompt}" if system_prompt else default_system
        if skill_context:
            system += f"\n\n## Skill files (repo/org-specific instructions)\n{skill_context}"

        prompt = f"""A dependency-ordered fix is about to be raised for this vulnerable package:

Package: {finding.get('package_name')}
Fixed version: {finding.get('fixed_version')}
Manifest: {finding.get('manifest_path')}
Severity: {finding.get('severity')}
Fix order computed (most foundational first): {order_summary}

Given any constraints in your skill files, decide whether to proceed. Respond with ONLY valid JSON:
{{"proceed": true or false, "skip_reason": "empty string if proceeding, else why you're skipping", "pr_title": "fix: ...", "pr_body": "1-3 sentence rationale for the fix, referencing the dependency order"}}"""
        return self._invoke_json(prompt, required_keys={"proceed", "pr_title", "pr_body"}, max_tokens=768, system_prompt=system)

    def judge_pattern_cluster(self, candidate_jobs: list[dict], min_occurrences: int) -> dict | None:
        jobs_desc = "\n".join(
            f"- {j['job_key']}: uses {', '.join(j['components'])}" for j in candidate_jobs
        )
        prompt = f"""You are looking for CI/CD jobs across a GitHub Actions monorepo that are functionally the same pattern and could share one reusable workflow template, even though their exact component lists differ slightly.

Candidate jobs (component signatures are similar but not identical):
{jobs_desc}

Judge whether these {len(candidate_jobs)} jobs are doing functionally the same thing (e.g. "build, test, and push a Docker image" is the same pattern even if one job has an extra lint step or a differently-ordered step list). If they are NOT genuinely the same pattern, respond with exactly: {{"is_match": false}}. If they ARE the same pattern and there are at least {min_occurrences} of them, respond with:
{{"is_match": true, "pattern_name": "short descriptive name", "draft_template_yaml": "a complete reusable workflow YAML (on: workflow_call) capturing the common shape, as a string with real newlines"}}
Respond with ONLY valid JSON, no other text."""
        result = self._invoke_json(prompt, required_keys={"is_match"}, max_tokens=2048)
        if not result.get("is_match") or "draft_template_yaml" not in result:
            return None
        return result
